latexdiff oopsla22-submission/main.tex oopsla22-camera-ready/main.tex > diff_tex/main.tex
latexdiff oopsla22-submission/introduction.tex oopsla22-camera-ready/introduction.tex > diff_tex/introduction.tex
latexdiff oopsla22-submission/overview.tex oopsla22-camera-ready/overview.tex > diff_tex/overview.tex
latexdiff oopsla22-submission/program-abstraction.tex oopsla22-camera-ready/program-abstraction.tex > diff_tex/program-abstraction.tex
latexdiff oopsla22-submission/seq-classifiers.tex oopsla22-camera-ready/seq-classifiers.tex > diff_tex/seq-classifiers.tex
latexdiff oopsla22-submission/whole-system.tex oopsla22-camera-ready/whole-system.tex > diff_tex/whole-system.tex
latexdiff oopsla22-submission/evaluation.tex oopsla22-camera-ready/evaluation.tex > diff_tex/evaluation.tex
latexdiff oopsla22-submission/related-work.tex oopsla22-camera-ready/related-work.tex > diff_tex/related-work.tex
latexdiff oopsla22-submission/conclusion.tex oopsla22-camera-ready/conclusion.tex > diff_tex/conclusion.tex
latexdiff oopsla22-submission/api.tex oopsla22-camera-ready/api.tex > diff_tex/api.tex
latexdiff oopsla22-submission/ecep-algo.tex oopsla22-camera-ready/ecep-algo.tex > diff_tex/ecep-algo.tex
latexdiff oopsla22-submission/evaluation-classifier-accuracy.tex oopsla22-camera-ready/evaluation-classifier-accuracy.tex > diff_tex/evaluation-classifier-accuracy.tex
latexdiff oopsla22-submission/parse-suggestion-example.tex oopsla22-camera-ready/parse-suggestion-example.tex > diff_tex/parse-suggestion-example.tex
latexdiff oopsla22-submission/partial-parse-example.tex oopsla22-camera-ready/partial-parse-example.tex > diff_tex/partial-parse-example.tex
latexdiff oopsla22-submission/predict-algo.tex oopsla22-camera-ready/predict-algo.tex > diff_tex/predict-algo.tex
latexdiff oopsla22-submission/seq2parse-architecture.tex oopsla22-camera-ready/seq2parse-architecture.tex > diff_tex/seq2parse-architecture.tex
latexdiff oopsla22-submission/syntax.tex oopsla22-camera-ready/syntax.tex > diff_tex/syntax.tex
latexdiff oopsla22-submission/training-classifier-algo.tex oopsla22-camera-ready/training-classifier-algo.tex > diff_tex/training-classifier-algo.tex